[package]
name = "openzeppelin-relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
log = "0.4"
simple_logger = "5.0.0"
dotenvy = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"